const tableData = [
  {
    id: 0,
    type: 0,
    date: "21 nov",
    time: "17:00",
    group: "A",
    points: "0",
    teamA: "SN",
    teamB: "NL",
    valueA: null,
    valueB: null,
  },
  {
    id: 1,
    type: 0,
    date: "20 nov",
    time: "17:00",
    group: "A",
    points: "0",
    teamA: "QA",
    teamB: "EC",
    valueA: null,
    valueB: null,
  },
  {
    id: 2,
    type: 0,
    date: "25 nov",
    time: "14:00",
    group: "A",
    points: "0",
    teamA: "QA",
    teamB: "SN",
    valueA: null,
    valueB: null,
  },
  {
    id: 3,
    type: 0,
    date: "25 nov",
    time: "17:00",
    group: "A",
    points: "0",
    teamA: "NL",
    teamB: "EC",
    valueA: null,
    valueB: null,
  },
  {
    id: 4,
    type: 0,
    date: "29 nov",
    time: "16:00",
    group: "A",
    points: "0",
    teamA: "NL",
    teamB: "QA",
    valueA: null,
    valueB: null,
  },
  {
    id: 5,
    type: 0,
    date: "29 nov",
    time: "16:00",
    group: "A",
    points: "0",
    teamA: "EC",
    teamB: "SN",
    valueA: null,
    valueB: null,
  },
  {
    id: 6,
    type: 1,
    date: "21 nov",
    time: "14:00",
    group: "B",
    points: "0",
    teamA: "EN",
    teamB: "IR",
    valueA: null,
    valueB: null,
  },
  {
    id: 7,
    type: 1,
    date: "21 nov",
    time: "20:00",
    group: "B",
    points: "0",
    teamA: "US",
    teamB: "WL",
    valueA: null,
    valueB: null,
  },
  {
    id: 8,
    type: 1,
    date: "25 nov",
    time: "11:00",
    group: "B",
    points: "0",
    teamA: "WL",
    teamB: "IR",
    valueA: null,
    valueB: null,
  },
  {
    id: 9,
    type: 1,
    date: "25 nov",
    time: "20:00",
    group: "B",
    points: "0",
    teamA: "EN",
    teamB: "US",
    valueA: null,
    valueB: null,
  },
  {
    id: 10,
    type: 1,
    date: "29 nov",
    time: "20:00",
    group: "B",
    points: "0",
    teamA: "WL",
    teamB: "EN",
    valueA: null,
    valueB: null,
  },
  {
    id: 11,
    type: 1,
    date: "29 nov",
    time: "20:00",
    group: "B",
    points: "0",
    teamA: "IR",
    teamB: "US",
    valueA: null,
    valueB: null,
  },
  {
    id: 12,
    type: 2,
    date: "22 nov",
    time: "11:00",
    group: "C",
    points: "0",
    teamA: "AR",
    teamB: "SA",
    valueA: null,
    valueB: null,
  },
  {
    id: 13,
    type: 2,
    date: "22 nov",
    time: "17:00",
    group: "C",
    points: "0",
    teamA: "MX",
    teamB: "PL",
    valueA: null,
    valueB: null,
  },
  {
    id: 14,
    type: 2,
    date: "26 nov",
    time: "14:00",
    group: "C",
    points: "0",
    teamA: "PL",
    teamB: "SA",
    valueA: null,
    valueB: null,
  },
  {
    id: 15,
    type: 2,
    date: "26 nov",
    time: "20:00",
    group: "C",
    points: "0",
    teamA: "AR",
    teamB: "MX",
    valueA: null,
    valueB: null,
  },
  {
    id: 16,
    type: 2,
    date: "30 nov",
    time: "20:00",
    group: "C",
    points: "0",
    teamA: "PL",
    teamB: "AR",
    valueA: null,
    valueB: null,
  },
  {
    id: 17,
    type: 2,
    date: "30 nov",
    time: "20:00",
    group: "C",
    points: "0",
    teamA: "SA",
    teamB: "MX",
    valueA: null,
    valueB: null,
  },
  {
    id: 18,
    type: 3,
    date: "22 nov",
    time: "14:00",
    group: "D",
    points: "0",
    teamA: "DK",
    teamB: "TN",
    valueA: null,
    valueB: null,
  },
  {
    id: 19,
    type: 3,
    date: "22 nov",
    time: "20:00",
    group: "D",
    points: "0",
    teamA: "FR",
    teamB: "AU",
    valueA: null,
    valueB: null,
  },
  {
    id: 20,
    type: 3,
    date: "26 nov",
    time: "11:00",
    group: "D",
    points: "0",
    teamA: "TN",
    teamB: "AU",
    valueA: null,
    valueB: null,
  },
  {
    id: 21,
    type: 3,
    date: "26 nov",
    time: "17:00",
    group: "D",
    points: "0",
    teamA: "FR",
    teamB: "DK",
    valueA: null,
    valueB: null,
  },
  {
    id: 22,
    type: 3,
    date: "30 nov",
    time: "16:00",
    group: "D",
    points: "0",
    teamA: "TN",
    teamB: "FR",
    valueA: null,
    valueB: null,
  },
  {
    id: 23,
    type: 3,
    date: "30 nov",
    time: "16:00",
    group: "D",
    points: "0",
    teamA: "AU",
    teamB: "DK",
    valueA: null,
    valueB: null,
  },
  {
    id: 24,
    type: 4,
    date: "23 nov",
    time: "14:00",
    group: "E",
    points: "0",
    teamA: "DE",
    teamB: "JP",
    valueA: null,
    valueB: null,
  },
  {
    id: 25,
    type: 4,
    date: "23 nov",
    time: "17:00",
    group: "E",
    points: "0",
    teamA: "ES",
    teamB: "CR",
    valueA: null,
    valueB: null,
  },
  {
    id: 26,
    type: 4,
    date: "27 nov",
    time: "11:00",
    group: "E",
    points: "0",
    teamA: "JP",
    teamB: "CR",
    valueA: null,
    valueB: null,
  },
  {
    id: 27,
    type: 4,
    date: "27 nov",
    time: "20:00",
    group: "E",
    points: "0",
    teamA: "ES",
    teamB: "DE",
    valueA: null,
    valueB: null,
  },
  {
    id: 28,
    type: 4,
    date: "1 dec",
    time: "20:00",
    group: "E",
    points: "0",
    teamA: "JP",
    teamB: "ES",
    valueA: null,
    valueB: null,
  },
  {
    id: 29,
    type: 4,
    date: "1 dec",
    time: "20:00",
    group: "E",
    points: "0",
    teamA: "CR",
    teamB: "DE",
    valueA: null,
    valueB: null,
  },
  {
    id: 30,
    type: 5,
    date: "23 nov",
    time: "11:00",
    group: "F",
    points: "0",
    teamA: "MA",
    teamB: "HR",
    valueA: null,
    valueB: null,
  },
  {
    id: 31,
    type: 5,
    date: "23 nov",
    time: "20:00",
    group: "F",
    points: "0",
    teamA: "BE",
    teamB: "CA",
    valueA: null,
    valueB: null,
  },
  {
    id: 32,
    type: 5,
    date: "27 nov",
    time: "14:00",
    group: "F",
    points: "0",
    teamA: "BE",
    teamB: "MA",
    valueA: null,
    valueB: null,
  },
  {
    id: 33,
    type: 5,
    date: "27 nov",
    time: "17:00",
    group: "F",
    points: "0",
    teamA: "HR",
    teamB: "CA",
    valueA: null,
    valueB: null,
  },
  {
    id: 34,
    type: 5,
    date: "1 dec",
    time: "16:00",
    group: "F",
    points: "0",
    teamA: "HR",
    teamB: "BE",
    valueA: null,
    valueB: null,
  },
  {
    id: 35,
    type: 5,
    date: "1 dec",
    time: "16:00",
    group: "F",
    points: "0",
    teamA: "CA",
    teamB: "MA",
    valueA: null,
    valueB: null,
  },
  {
    id: 36,
    type: 6,
    date: "24 nov",
    time: "11:00",
    group: "G",
    points: "0",
    teamA: "CH",
    teamB: "CM",
    valueA: null,
    valueB: null,
  },
  {
    id: 37,
    type: 6,
    date: "24 nov",
    time: "20:00",
    group: "G",
    points: "0",
    teamA: "BR",
    teamB: "RS",
    valueA: null,
    valueB: null,
  },
  {
    id: 38,
    type: 6,
    date: "28 nov",
    time: "11:00",
    group: "G",
    points: "0",
    teamA: "CM",
    teamB: "RS",
    valueA: null,
    valueB: null,
  },
  {
    id: 39,
    type: 6,
    date: "28 nov",
    time: "17:00",
    group: "G",
    points: "0",
    teamA: "BR",
    teamB: "CH",
    valueA: null,
    valueB: null,
  },
  {
    id: 40,
    type: 6,
    date: "2 dec",
    time: "20:00",
    group: "G",
    points: "0",
    teamA: "CM",
    teamB: "BR",
    valueA: null,
    valueB: null,
  },
  {
    id: 41,
    type: 6,
    date: "2 dec",
    time: "20:00",
    group: "G",
    points: "0",
    teamA: "RS",
    teamB: "CH",
    valueA: null,
    valueB: null,
  },
  {
    id: 42,
    type: 7,
    date: "24 nov",
    time: "14:00",
    group: "H",
    points: "0",
    teamA: "UY",
    teamB: "KR",
    valueA: null,
    valueB: null,
  },
  {
    id: 43,
    type: 7,
    date: "24 nov",
    time: "17:00",
    group: "H",
    points: "0",
    teamA: "PT",
    teamB: "GH",
    valueA: null,
    valueB: null,
  },
  {
    id: 44,
    type: 7,
    date: "28 nov",
    time: "14:00",
    group: "H",
    points: "0",
    teamA: "KR",
    teamB: "GH",
    valueA: null,
    valueB: null,
  },
  {
    id: 45,
    type: 7,
    date: "28 nov",
    time: "20:00",
    group: "H",
    points: "0",
    teamA: "PT",
    teamB: "UY",
    valueA: null,
    valueB: null,
  },
  {
    id: 46,
    type: 7,
    date: "2 dec",
    time: "16:00",
    group: "H",
    points: "0",
    teamA: "KR",
    teamB: "PT",
    valueA: null,
    valueB: null,
  },
  {
    id: 47,
    type: 7,
    date: "2 dec",
    time: "16:00",
    group: "H",
    points: "0",
    teamA: "GH",
    teamB: "UY",
    valueA: null,
    valueB: null,
  },
];

const groupsScheme = [
  {
    group: "A",
    teams: ["NL", "EC", "QA", "SN"],
  },
  {
    group: "B",
    teams: ["US", "WL", "IR", "EN"],
  },
  {
    group: "C",
    teams: ["AR", "SA", "MX", "PL"],
  },
  {
    group: "D",
    teams: ["FR", "AU", "DK", "TN"],
  },
  {
    group: "E",
    teams: ["CR", "JP", "ES", "DE"],
  },
  {
    group: "F",
    teams: ["BE", "MA", "HR", "CA"],
  },
  {
    group: "G",
    teams: ["RS", "BR", "CM", "CH"],
  },
  {
    group: "H",
    teams: ["GH", "PT", "KR", "UY"],
  },
];

const roundOf16Scheme = [
  {
    match: 1,
    teamA: "A1",
    teamB: "B2",
    date: "2 dec",
    time: "16:00",
  },
  {
    match: 2,
    teamA: "C1",
    teamB: "D2",
    date: "2 dec",
    time: "20:00",
  },
  {
    match: 3,
    teamA: "D1",
    teamB: "C2",
    date: "3 dec",
    time: "16:00",
  },
  {
    match: 4,
    teamA: "B1",
    teamB: "A2",
    date: "3 dec",
    time: "20:00",
  },
  {
    match: 5,
    teamA: "E1",
    teamB: "F2",
    date: "4 dec",
    time: "16:00",
  },
  {
    match: 6,
    teamA: "G1",
    teamB: "H2",
    date: "4 dec",
    time: "20:00",
  },
  {
    match: 7,
    teamA: "F1",
    teamB: "E2",
    date: "5 dec",
    time: "16:00",
  },
  {
    match: 8,
    teamA: "H1",
    teamB: "G2",
    date: "5 dec",
    time: "20:00",
  },
];

const quarterScheme = [
  {
    match: 1,
    teamA: "WG5",
    teamB: "WG6",
    date: "9 dec",
    time: "16:00",
  },
  {
    match: 2,
    teamA: "WG1",
    teamB: "WG2",
    date: "9 dec",
    time: "20:00",
  },
  {
    match: 3,
    teamA: "WG7",
    teamB: "WG8",
    date: "10 dec",
    time: "16:00",
  },
  {
    match: 4,
    teamA: "WG4",
    teamB: "WG3",
    date: "10 dec",
    time: "20:00",
  },
];

const semiScheme = [
  {
    match: 1,
    teamA: "WG2",
    teamB: "WG1",
    date: "13 dec",
    time: "20:00",
  },
  {
    match: 2,
    teamA: "WG4",
    teamB: "WG3",
    date: "14 dec",
    time: "20:00",
  },
];

const thirdPlaceScheme = [
  {
    match: 1,
    teamA: "LG1",
    teamB: "LG2",
    date: "17 dec",
    time: "20:00",
  },
];

const finalScheme = [
  {
    match: 1,
    teamA: "WG1",
    teamB: "WG2",
    date: "18 dec",
    time: "20:00",
  },
];

const headingData = {
  title: {
    text: "Sweepstakes",
  },
  content: {
    text: "Try to predict the world cup matches and win grand prizes!",
    color: "stable-700",
  },
};

const cardRulesData = {
  icon: {
    name: "info",
  },
  title: {
    text: "Rules",
  },
  content: {
    text: "Make sure to fill in all rounds before submitting",
    color: "stable-700",
  },
  rules: [
    {
      icon: {
        name: "checkmark-double",
      },
      content: {
        text: "3 points: Predict match score and winner",
      },
      subtext: {
        text: "5 points: If the match includes your world cup team",
      },
    },
    {
      icon: {
        name: "checkmark",
      },
      content: {
        text: "1 points: Predict the winning team",
      },
      subtext: {
        text: "3 points: if the match includes your world cup team",
      },
    },
    {
      icon: {
        name: "cross",
      },
      content: {
        text: "0 points: Predict wrong",
        color: "assertive",
      },
    },
  ],
};

const examplesData = [
  {
    icon: {
      name: "create",
      color: "energized",
    },
    title: {
      text: "Form",
    },
    content: {
      text: "Fill in your predictions for all rounds",
      color: "stable-700",
    },
  },
  {
    icon: {
      name: "shirt",
      color: "positive",
    },
    title: {
      text: "Confirm",
    },
    content: {
      text: "Make sure to double check your predictions",
      color: "stable-700",
    },
  },
  {
    icon: {
      name: "document-locked",
      color: "balanced",
    },
    title: {
      text: "Submit",
    },
    content: {
      text: "Submit your predictions as a transaction",
      color: "stable-700",
    },
  },
];

const ctaData = {
  title: {
    text: "Be the next DaGoats champion",
  },
  content: {
    text: "Predict all matches and win $GOAT tokens!",
  },
  button: {
    text: "Read more",
    textColor: "light",
  },
  image: "https://dagoats.io/wp-content/uploads/2022/06/maradona.png",
};

const timelineData = {
  rounds: [
    {
      text: "Groups",
    },
    {
      text: "Ro16",
    },
    {
      text: "Quarter",
    },
    {
      text: "Semi",
    },
    {
      text: "3rd",
    },
    {
      text: "Final",
    },
  ],
};

const profileData = {
  tokens: [
    {
      title: {
        text: "SOL",
      },
      content: {
        text: "token",
      },
      available: 0.25,
      required: 0.25,
    },
    {
      title: {
        text: "DUST",
      },
      content: {
        text: "token",
      },
      available: 5,
      required: 7,
    },
    {
      title: {
        text: "DGOAT",
      },
      content: {
        text: "token",
      },
      available: 250,
      required: 500,
    },
    {
      title: {
        text: "MVP",
      },
      content: {
        text: "token",
      },
      available: 750,
      required: 750,
    },
    {
      title: {
        text: "LABS",
      },
      content: {
        text: "token",
      },
      available: 375,
      required: 375,
    },
  ],
};

export {
  tableData,
  groupsScheme,
  roundOf16Scheme,
  quarterScheme,
  semiScheme,
  thirdPlaceScheme,
  finalScheme,
  headingData,
  cardRulesData,
  examplesData,
  ctaData,
  timelineData,
  profileData,
};
